### ISSUE TITLE
Model Setup External module for R9M FCC-LBT power selection option no longer shows up and overwrites CH number

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#10]
**Describe the bug**
In the model setup page you the R9M external module selection for FCC or Euro is not formatted correctly and overwrites the channel number selection....

**To Reproduce**
turn off internal module and select R9M for external module options

**Comment by derdoktor667** [comment]
...same for all externals with channel selection ...has to wait until I cleaned up my mess and rearrange the codebase to be more "OpenTXish" ...new sources are much clearer and have better structure.

 [(if ..... else if ..... if(PCB1234) || (PCB4321) && this -> kill.me)] 

....you know what I'm talking about.

**Comment by derdoktor667** [comment]
....one fixed, one other broke ....the circle of life 
- commit: ....make it work again:
https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/commit/e5e570c0f0d6147917bb8ee8ceabe72f1ba4a48b

best regards
