### ISSUE TITLE
Unable to compile - Size of flash "overflowed" with most recent merges

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#11]
**Describe the bug**
A few days ago I was able to compile your firmware without a problem but today I tried with your recent changes and am getting a "Flash Overflow by 30176 bytes".  Is it possible you exceeded the flash of the board?

/usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/bin/ld: ../../firmware.elf section `.text' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/6.3.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 30176 bytes
collect2: error: ld returned 1 exit status
radio/src/CMakeFiles/firmware.dir/build.make:6924: recipe for target 'firmware.elf' failed
make[3]: *** [firmware.elf] Error 1
CMakeFiles/Makefile2:177: recipe for target 'radio/src/CMakeFiles/firmware.dir/all' failed
make[2]: *** [radio/src/CMakeFiles/firmware.dir/all] Error 2
CMakeFiles/Makefile2:189: recipe for target 'radio/src/CMakeFiles/firmware.dir/rule' failed
make[1]: *** [radio/src/CMakeFiles/firmware.dir/rule] Error 2
Makefile:144: recipe for target 'firmware' failed
make: *** [firmware] Error 2

**To Reproduce**
Compile using cmake under linux

**Comment by derdoktor667** [comment]
....hmmm, I´m getting Firmware size: 2036.55 KB (99.44 %) by TravisCI, my "default" builder Ubuntu 19.04 „Disco Dingo“ said Firmware size: 2036.62 KB (99.44 %) and Windows 10 Build 1903 WSL returned Firmware size: 2041.50 KB (99.68 %) to me ....the compilers in all systems are installed by using only "apt-get" packets to make it easier to "rebuild" a machine. ....what build command did you use??? ...I attach the latest "build output" created by the Ubuntu machine ...keeping this "open" for now 

[build_output_140819.txt](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3502938/build_output_140819.txt)

**Comment by TimothyGold** [comment]
Using your cmake options - 
cmake -DPCB=NV14 -DGVARS=OFF -DLUA=ON -DHELI=OFF -DLUA_COMPILER=ON -SIMU_AUDIO=OFF -DSIMU_LUA_COMPILER=OFF -DUSB_SERIAL=ON -DHELI=OFF -DALLOW_NIGHTLY_BUILDS=ON -DAUTOSWITCH=ON -DAUTOSOURCE=ON -DGUI=ON -DBOOTLOADER=ON -DDISABLE_COMPANION=OFF -DCMAKE_BUILD_TYPE=Release ../

Attached is my compile output for Ubuntu - 

[TG_buildoutput_8-14-19.txt](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3502993/TG_buildoutput_8-14-19.txt)

**Comment by derdoktor667** [comment]
....good one ...try clean your build dir by some kind of simple "make clean" or try "git clear --force" and rebuild ....in the meantime I´m adapting the latest changes pushed by FlySky

**Comment by TimothyGold** [comment]
I usually do a make clean and also a git reset --hard.  I will try to re-base again and see what happens...

**Comment by derdoktor667** [comment]
....what about running "python3 ./tools/utilize_docker.py" in the base dir???

**Comment by TimothyGold** [comment]
I did get your script to finally work after installing the Qt libraries.  didn't have them because I was just building the firmware.  Although the build is now failing after your last merge.  I'm sure you are aware.

**Comment by TimothyGold** [comment]
I just tried the fork https://github.com/open-flysky/Flysky-OpenTX-Test-Branch and everything compiles and loads to the radio without overflow on this fork.

**Comment by derdoktor667** [comment]
....that´s what I´m talking about ....need some time to read the "changes"

**Comment by TimothyGold** [comment]
I am now able to compile without the overflow.  I think this may have been that I loaded the libraries recommended for opentx 2.2 and not 2.1.  I reinstalled all the recommendations including the QT libraries and everything seems to compile fine now.

**Comment by derdoktor667** [comment]
....did you see the latest changes already ....also pushed a pic of bootloader screen
