### ISSUE TITLE
System crashes when trying to select a different model

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#12]
**Describe the bug**
Some of the changes to implement a new model script ultimately causes the system to crash when trying to select a different model.

**To Reproduce**
Select a new model

**Comment by derdoktor667** [comment]
...in my opinion, you may start with a fresh clone ....I can´t see where any problems are ...did you copy the new wizard scripts to your sdcard??? ...closed

**Comment by TimothyGold** [comment]
All scripts are copied including the theme options for the new model scripts.  latest release of yours and Open-Flysky crashes when switching models.  Even happens when switching to a newly created model using the wizard.  Crash goes away if I go back to the compile right before the work on the new model wizard...

**Comment by derdoktor667** [comment]
....did you remove the WIDGETS??? ...with LUA widgets in sdcard folder it will crash ...it´s a known problem ...just at the moment I flashed the latest compiler output and can create new models, switch, duplicate, delete them without any problems ...my guess is still your sdcard content ...sorry for that ...I hope future builds will work as usual for you ...thanks for your feedback

**Comment by TimothyGold** [comment]
Thanks for reminding me about the WIDGETS problem.  I had it deleted before but made some changes in the SD structure in the last couple of days and forgot it was there in my backup.  Also Not sure if you are seeing the same problem but firmware update feature is not working again.  It resets power but then shuts down completely and then when plugging in USB it starts to charge.  Still have to enter DFU via button.  Thanks again for all your work on this....

**Comment by derdoktor667** [comment]
.....the firmware update button will be removed, as you can flash firmware using the bootloader

![NV14_bootloader](https://user-images.githubusercontent.com/2376997/63111224-825df380-bf8d-11e9-8096-f43f4d4b303a.jpg)

**Comment by TimothyGold** [comment]
how do I enter the bootloader?

**Comment by derdoktor667** [comment]
....https://bit.ly/2YZ7UAr

**Comment by TimothyGold** [comment]
:) LOL... I didn't even put 2 and 2 together until I remembered having to do this in the Taranis.  I must be doing something wrong though on the NV14 no mater what I do I cannot get it to power on while holding the 2 trims.  I held it for a long time and it never did power on.  I tried to hold for short period and never did boot into the bootloader.  The only way I could get the screen to show up was while holding the trim tabs I plugged the usb in and then it quickly moves pasted the bootloader screen and says usb connected.  Then goes away after I unplug.  Is there a trick while holding both power buttons?  Sorry to be such a pain..  Should be pretty straight forward....

**Comment by derdoktor667** [comment]
....nope, I push the trims and fire up the radio ....that´s it ....it´s called "BOOTLOADER_MAGIC" but it´s not witchcraft ....but wait, I think I can "transform" the UpgradeButton to some kind of "Reboot into Bootloader" thing ....maybe ....I´ll have a look

**Comment by TimothyGold** [comment]
No matter what I try I cannot get it to power up while holding the Ail and Rudder trims together.  I can see the screen kind of go black active but never boots in any way.

**Comment by TimothyGold** [comment]
Well I must have missed one of your changes from yesterday in the firmware I have been working with.  I pulled your most recent and now bootloader works....    This is awesome.  Thanks again for your support...

**Comment by derdoktor667** [comment]
....flash the latest "release" ...and at the weekend I change the button ...and away for today ;o)
