### ISSUE TITLE
Mixer Line item set to source = 0 (null) keeps all lower mixes from working.

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#13]
**Describe the bug**
I had a case where I needed to just disable a mix in the mixer list but didn't want to delete the whole mix because I wanted to use it again.  So I just set the source to 0 or (--).  What I found is that every mix below this mix stopped working.  The only way I could get the lower mixes to start working again was to delete the mix.  I looked at mixes.cpp and tried a few things but could not find the problem.  

**To Reproduce**
Set a mix source in the middle of the list to --.

**Comment by derdoktor667** [comment]
...you can read here: https://www.rcgroups.com/forums/showpost.php?p=42523139&postcount=2615
...no more to say

**Comment by TimothyGold** [comment]
Yes that is my comment on rcgroups.  I did try this and it did not work.  Something else must be causing this issue not the edit in line 816...

**Comment by derdoktor667** [comment]
...will maybe fixed by a commit by eshifri ....in the evening I'm going to test it by myself in "real world" ....be prepared :wink:
