### ISSUE TITLE
SWG Radio setup only allows 2 POS - Special Functions SWF Center position does not work to trigger

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#14]
**Describe the bug**
I noticed 2 bugs while trying create Special functions for the 2 lower 3 pos switches SWF and SWG.  I noticed first that I could not get a special function to trigger on the middle position of SWF.  I then just decided to use SWG but then found that there is a issue in the Radio Hardware setup for SWG where it by default allows 3 position but in the popup menu it only allows you to set none, trigger, or 2Pos.

**Comment by eshifri** [comment]
radio_hardware.cpp:
#define SWITCH_TYPE_MAX(sw)            ((MIXSRC_SB-MIXSRC_FIRST_SWITCH == sw || MIXSRC_SF-MIXSRC_FIRST_SWITCH == sw || MIXSRC_SH-MIXSRC_FIRST_SWITCH == sw) ? SWITCH_3POS : SWITCH_2POS)
It should be MIXSRC_SG - not MIXSRC_SH

SF problem is trickier: it is 3 pos switch everywhere outside special functions that control AUDIO.
I hoped the problem is in getSwitchesPosition() since it has incorrect descriptions for NV14, but turned out it does not affect special functions.

**Comment by eshifri** [comment]
With SWF it turned to be getSwitchesPosition() after all.
I will put fixies into my stream.

**Comment by TimothyGold** [comment]
Nice catch on the SWG. This did work to reset the options for 3pos.  I did implement your changes to try and fix Special functions for SWF but middle position does not select for any audio either play sound or play track.  The SWF down does get triggered with the middle position switch.  Its like its a 2 pos switch but only in Special functions.  It works as a 3 position switch everywhere else.

**Comment by TimothyGold** [comment]
@eshifri I ended up taking a closer look at your changes and SWF is fixed with your changes.  Hopefully all forks can see this and then pull these in.  Thanks for your help.

**Comment by qba667** [comment]
@derdoktor667 @eshifri  Hi Guys, what is status of this repository?
I like changes you are doing - but because you are changing so much we can lose possibility to merge it back. Keep in mind that target is to get back into official OpenTX repository.

**Comment by eshifri** [comment]
@qba667  My fork is synchronized with open-flysky and I'm submitting pull requests regularly.
I'm afraid that @derdoktor667 fork is very different and I'm not sure you will want all his changes in official stream: e.g. current implementation of switch warnings is better in open-flysky than here (they came from me, so I hope I'm not offending anybody :-) ), so we will have to do very selective merges at some point.
