### ISSUE TITLE
Remove Loop of "RX Still connected" and ask for confirmation

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#3]
I noticed that you have most of the fixes out there but there is one that I implemented but then didn't have time to keep going with it.  

Below will give the option to remove the never ending loop when trying to shutdown the TX while Telem is still connected.  There is a catch in there that checks for NV14 then just loops because no one spent the time to implement the required popup.

uint32_t pwrCheck()
{
  const char * message = NULL;

  enum PwrCheckState {
    PWR_CHECK_ON,
    PWR_CHECK_OFF,
    PWR_CHECK_PAUSED,
  };

  static uint8_t pwr_check_state = PWR_CHECK_ON;

  if (pwr_check_state == PWR_CHECK_OFF) {
    return e_power_off;
  }
  else if (pwrPressed()) {
    if (TELEMETRY_STREAMING()) {
      message = STR_MODEL_STILL_POWERED;
    }
    if (pwr_check_state == PWR_CHECK_PAUSED) {
      // nothing
    }
    else if (pwr_press_time == 0) {
      pwr_press_time = get_tmr10ms();
      if (message && !g_eeGeneral.disableRssiPoweroffAlarm) {
        audioEvent(AU_MODEL_STILL_POWERED);
      }
    }
    else {
      inactivity.counter = 0;
      if (g_eeGeneral.backlightMode != e_backlight_mode_off) {
        BACKLIGHT_ENABLE();
      }
      if (get_tmr10ms() - pwr_press_time > PWR_PRESS_SHUTDOWN_DELAY) {
        if (TELEMETRY_STREAMING() && !g_eeGeneral.disableRssiPoweroffAlarm){
        new Dialog(WARNING_TYPE_INPUT, "Shut Down", "PWR Off TX?", [=]() {
            // power off
            haptic.play(15, 3, PLAY_NOW);
            pwr_check_state = PWR_CHECK_OFF;
            return e_power_off;
        });
        // shutdown has been cancelled
        pwr_check_state = PWR_CHECK_PAUSED;
        return e_power_on;
        }
        else {
            haptic.play(15, 3, PLAY_NOW);
            pwr_check_state = PWR_CHECK_OFF;
            return e_power_off;
        }
      }
      else {
        drawShutdownAnimation(pwrPressedDuration(), message);
        return e_power_press;
      }
    }
  }
  else {
    pwr_check_state = PWR_CHECK_ON;
    pwr_press_time = 0;
  }

  return e_power_on;
}

**Comment by derdoktor667** [comment]
....hm, I think I´ll give the "new way" a shot ....we will see.
