### ISSUE TITLE
Crash during boot

### ISSUE THREAD

**Issue by eshifri** [derdoktor667/Flysky-OpenTX-Test-Branch#5]
Looks like I'm the only one having this problem, but for me "stable" build crashes while displaying the splash screen.

**Comment by derdoktor667** [comment]
....nice ;) ...what about your sdcard??? ...and are you using an external module???

**Comment by eshifri** [comment]
I do not have external module. My SD card is the same I'm using with all other builds: Widgets folder renamed, audio package is an extended one, two models and color PNG model icons of standard size.

**Comment by derdoktor667** [comment]
....ok, we will need a log for this ....but just for now, would you mind unplugging your external and give it a try? ...the "shortest" answer would be, "Factory Reset", rewrite Firmware, "Factory Reset", cross fingers ...but we don´t want to loose any settings ....or force any user to reset the NV14, don´t we ;)
