### ISSUE TITLE
This branch does not compile natively on Windows 10

### ISSUE THREAD

**Issue by eshifri** [derdoktor667/Flysky-OpenTX-Test-Branch#6]
make firmware returns an error:
Building CXX object radio/src/CMakeFiles/firmware.dir/targets/nv14/telemetry_driver.cpp.obj
arm-none-eabi-g++: error: unrecognized command line option '-std=gnu++1y'
radio\src\CMakeFiles\firmware.dir\build.make:61: recipe for target 'radio/src/CMakeFiles/firmware.dir/targets/nv14/telemetry_driver.cpp.obj' failed
make[3]: *** [radio/src/CMakeFiles/firmware.dir/targets/nv14/telemetry_driver.cpp.obj] Error 1

I'm using the same build tools as for all other branches: cmake -G "MinGW Makefiles"

**Comment by TimothyGold** [comment]
Same problem when I try. I can build your other branch fine.

**Comment by derdoktor667** [comment]
....use docker image or follow the readme ....compiles on docker, travis (https://travis-ci.com/derdoktor667/Flysky-OpenTX-Test-Branch/jobs/217839958) ...my windows version at the moment 1903.

....don´t know your setup but for the case you can´t get it compile on your machine I really suggest to use the docker image.
