### ISSUE TITLE
Logical switch menu's for Sticky and AND switches not showing correctly

### ISSUE THREAD

**Issue by RadianceNL** [derdoktor667/Flysky-OpenTX-Test-Branch#7]
**Describe the bug A clear and concise description of what the bug is.**
The menu's for the logical switch options Sticky and AND are overlapping each other which makes it impossible to set the correct value's.

**To Reproduce Steps to reproduce the error and conditions:**
Because the menu items in those menu's are overlapping each other I can't set the right settings in the right form. The settings I want to enter in the V2 form are actually applied to the AND switch form.

**Expected behavior A clear and concise description of what you expected to happen.**
The menu items should be shown in a clean list so you can see which form you're actually editing

**Screenshots or Docker Logs Be sure to add at least one of them.**
Sticky menu
Overlapping menu:
https://radiancefpv.nl/img/sticky_bad.jpg
Good menu:
https://radiancefpv.nl/img/sticky_good.jpg
AND menu
Overlapping menu:
https://radiancefpv.nl/img/and_bad.jpg
Good menu
https://radiancefpv.nl/img/and_good.jpg

**Firmware used**
firmware_210719_testing_nv14.bin
firmware_130719_stable_nv14.bin

**Comment by RadianceNL** [comment]
Problem still exists in your latest build **firmware_030819_fixed_nv14.bin**

**Comment by derdoktor667** [comment]
....nice report, Sir ;) ...I think it will be a small fix ...looking at this at once

best regards

**Comment by eshifri** [comment]
In case you have not find it yet :-): lines 80 - 86 in model_logical_switches.cpp should be removed.
They may have other unpleasant effects as well.

**Comment by derdoktor667** [comment]
....thank you, eshifri ...I was thinking about some "strange" parts on this file just at this moment ....a screen by the way 
![Unbenannt](https://user-images.githubusercontent.com/2376997/62480923-5b473b00-b7b1-11e9-9897-9162bd555010.PNG)

**Comment by derdoktor667** [comment]
...ok, try this version ...have my hardware not with me ´till weekend, sorry

[firmware_logical_fix_testing_050819_NV14.zip](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3468628/firmware_logical_fix_testing_050819_NV14.zip)

**Comment by derdoktor667** [comment]
....reported working by a trusted "beta tester" ...thank you all and closed

**Comment by RadianceNL** [comment]
The issue is fixed in the firmware you just uploaded in this thread.
I see if I can test this firmware this week but otherwise I will flash back a stable build I have on my computer because I'm going on holiday this Friday and need a working radio with me ;-)

Btw, I know this ain't a support forum but I get time sync errors with Docker on Windows which results in an incomplete configuration error. Googled and tried a lot but I'm unable to build your firmware myself. Getting errors with QT creator as well btw.
See my docker logs:
[CMakeError.log](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3468907/CMakeError.log)
[CMakeOutput.log](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3468908/CMakeOutput.log)

**Comment by derdoktor667** [comment]
...thank you for testing and your support, RadianceNL ....maybe this or these guys can help:
https://stackoverflow.com/questions/3824500/compiling-c-on-remote-linux-machine-clock-skew-detected-warning

**Comment by RadianceNL** [comment]
Thanks but I've found that thread myself as well but didn't find a solution. Also tried to change the NTP servers on Windows to a different, recommended one, but didn't help either. Only thing I can think of I read in the Stackoverflow thread now is to change my motherboard battery. Recently had a corrupt BIOS as well so that's where the problem might be...otherwise I don't know. Will report back later!

Thank you for your time and effort you put into this firmware!

**Comment by RadianceNL** [comment]
Flew with the firmware today and didn't experience any issues. Also works fine with LiftOff so I guess it's safe to take it with me on holiday.

**Comment by derdoktor667** [comment]
...thank you and have a nice holiday
