### ISSUE TITLE
firmware_210719_testing_nv14.bin Trainer capture fails

### ISSUE THREAD

**Issue by TimothyGold** [derdoktor667/Flysky-OpenTX-Test-Branch#8]
I tried your latest release and the trainer capture as Master no longer works.

**Comment by derdoktor667** [comment]
...I think this is built without your latest patches ...will check on it

**Comment by derdoktor667** [comment]
....sorry, but need more info about issue ...never used a "trainer" and this is why I have to wait for "somebody" else to fix this
