### ISSUE TITLE
Telemetry sensors

### ISSUE THREAD

**Issue by CharlesGauci** [derdoktor667/Flysky-OpenTX-Test-Branch#9]
Hi,
I don't know if you can help me but I would appreciate if you do. 

Can the 'Ratio' in the sensor edit list be changed to allow negative values, say '-1000'?

I use the altitude sensor fs-cat01. The air pressure reading in the Telemetry sensors is more or less correct. I created a copy with UNIT in meters (M).

I am trying different settings on the RATIO option to no avail, the altitude gives a negative measure. 

I believe that the UNIT or the RATIO icon is the problem. Is there a way you can help me out with this issue? I asked about this in RC Groups months ago but I had no luck.

Once again I would like to thank you for the excellent work that you are doing, thanks also to Eshifri who is supporting you a lot.

**Comment by eshifri** [comment]
Hi CharlesGauci,
I do not have this sensor, so I cannot try it, but if you need a negative RATIO value it is line 273 of model_telemetry.cpp:
 new NumberEdit(sensorOneWindow, grid.getFieldSlot(), 0, 30000,
                             GET_SET_DEFAULT(sensor->custom.ratio));
so it might be sufficient to change 0 to -3000.
May be derdoktor667 can create a build for you to try.
I can do it on my branch but it is rather different from this one, so I would suggest against switching to it if you are happy with current performance in other aspects.

**Comment by derdoktor667** [comment]
....one moment guys

**Comment by derdoktor667** [comment]
....here you are, Sir 

[firmware_telemetrix_test_060819_nv14.zip](https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch/files/3473121/firmware_telemetrix_test_060819_nv14.zip)

**Comment by derdoktor667** [comment]
....yes / no / maybe??? ...closed ´till negatives

**Comment by CharlesGauci** [comment]
Thanks a lot to both of you, will try it tomorrow as my wife is complaining to take her out for a drink :)

**Comment by CharlesGauci** [comment]
Good morning, installed it half an hour ago.

Ratio from default zero I press 'MIN' value becomes 62536. It looks like a plus number not minus.
Ratio from default zero I press '<<' value becomes 65526. Plus not minus.
Ratio from default zero I press '-' value becomes 65535 plus.
from '<< 65526' I pressed '-' value became 30,000 so I tried pressing '<<' several times which decreased by ten each time. when I reached zero (that is after 3000 times) the value came back to 65526 plus.  

I cannot find a way to get a value in minus.


Sorry for the bad news,

Charles

**Comment by eshifri** [comment]
Sorry, my bad: ratio is unsigned for every telemetry sensor. 
It is more complicated than I hoped.

**Comment by eshifri** [comment]
Looks like the only negative value supported is for OFFSET. And offset is used as a multiplier in the code.
It is also possible that this sensor is not supported yet.

**Comment by CharlesGauci** [comment]
Thank you for trying anyway. I do not think that the sensor is not supported yet at the air pressure right now is reading 1011.8 which is very close to the average atmospheric pressure of 1013.25.

I made a query in RC Groups on the 28th of March and QBA667 replied that he was going to use the algorithm that he did on the FS-I6, but this never happened. I wrote a reminder on the 13th of May but I am feeling shy to ask him again. Maybe one day he will implement it.

**Comment by eshifri** [comment]
I have fond Jakub's implementation for FS-i6: https://github.com/qba667/FlySkyI6/commit/094ad2a537946d68ecfcaec5d4fdf3b6996e181c
It is rather involved and requires significant telemetry signal processing.
I'm afraid your best bet is to wait for him to port it or ask him again.
Looks like changes to the formula parameters will not do it.

**Comment by eshifri** [comment]
Krauss, sorry for converting your bug reports page into discussion forum. :-)

**Comment by derdoktor667** [comment]
....no problem, guys ...short question: ...the negatives doesn´t work, right???

**Comment by CharlesGauci** [comment]
That's it, when I press the negative a value in plus comes in.

**Comment by CharlesGauci** [comment]
I am not feeling comfortable to ask Jakub for the third time, someone commented that I am creating a fuss about something when other more important topics still need to be done on this radio. 

For me, being a thermal soarer, it is useless without an altitude sensor. In fact, I am considering to order the Paladin in the near future.

**Comment by derdoktor667** [comment]
...sorry for that ...I don´t have any telemetrics to work with it. I reverted yesterdays commit ...do you really think the "Paladin" is the better radio??? ...saw only pics, and on these the Paladin looks a bit "cheap"

**Comment by CharlesGauci** [comment]
So if I reinstall your current release should it delete yesterday's update? I can still leave it as it is as I will not be using the minus tabs anyway. 

The Nirvana is much nicer of course but the Paladin is the only other Flysky radio which gives voice telemetry values. I am still inquiring whether it is compatible with my current fs-ia6b and fs-ia10b receivers.

**Comment by derdoktor667** [comment]
...today will be no release ...the one you installed is a custom version (compiled) ...today I just reverted the change eshifri suggested ...I think, keep it until next release (this weekend???)
...hmmm, I thought the Paladin will be an AFHDS3 radio ...will it be able to adapt an AFHDS2 receiver incl. telex???

**Comment by CharlesGauci** [comment]
Yesterday I asked Flysky in RC Groups 'New listing PL18 ' if they are compatible and still waiting for a reply. Probably it will need a separate rf module.

**Comment by eshifri** [comment]
I have found that Altitude sensor is processed in telemetry_nv14.cpp  and all constants are hard-coded there.

**Comment by CharlesGauci** [comment]
I think I found it, seems like those are for air pressure which is working fine. Could it be line 67 'Air Pressure Alt'  Unit Meters which is giving opposite values? 

I really appreciate your help

**Comment by eshifri** [comment]
There is a function CalculateAltitude() at line 97 that has all constants hard-coded.
It is called from the line 173. Something is not correct around these areas.

**Comment by CharlesGauci** [comment]
Do you think, if there is a way, we should forward this conversation to qba667 maybe he can help us?

**Comment by derdoktor667** [comment]
....sure ...why not ...it´s not "mine" ......it´s "ours" ;)

**Comment by CharlesGauci** [comment]
Hi,

I made the courage to open the issue in the Chevyhu Branch and Jakub replied, he intends to change the whole algorithm when he finds the test version of it as it is much better.

**Comment by CharlesGauci** [comment]
Good morning Mr Wasl Kraus, I noted that qba667 committed a new ibus telemetry update last night which seems to include altitude readings as well. By any chance are you planning to include this in your next release? Have a nice weekend, Charles

**Comment by derdoktor667** [comment]
....I really don´t know ....I don´t own any telemetric devices. ....and because of this, I can´t say if it is working ....and as I don´t use it, I don´t need it ....we will see
